version: '2'

services:
  express-mongoose-es6-rest-api:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4040:4040"
    env_file:
      - .env
    # Overwrite any env var defined in .env file (if required)
    environment:
      - MONGO_HOST=mongodb://mongo/express-mongoose-es6-rest-api-development
      - DEBUG=express-mongoose-es6-rest-api:*
    links:
      - mongo
  mongo:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
